version: '3.7'

services:
  gilfoyle:
    restart: on-failure
    build:
      context: ../../
      dockerfile: .support/docker/Dockerfile
    command:
      - "serve"
      - "-p"
      - "3000"
    ports:
      - 3000:3000

  postgres:
    image: postgres:latest
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: gilfoyle
      POSTGRES_PASSWORD: secret

  rabbitmq:
    image: rabbitmq:3.8-alpine
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: gilfoyle
      RABBITMQ_DEFAULT_PASS: secret
    ports:
      - 5672:5672
