definitions:
  ent.Video:
    properties:
      created_at:
        type: string
      id:
        type: string
      status:
        type: string
      title:
        type: string
      updated_at:
        type: string
    type: object
  httputils.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  httputils.HTTPResponse:
    properties:
      code:
        example: 200
        type: integer
      data:
        type: object
    type: object
info:
  contact: {}
  license:
    name: GNU General Public License v3.0
    url: https://github.com/dreamvo/gilfoyle/blob/master/LICENSE
paths:
  /health:
    get:
      responses:
        "200": {}
      summary: Check service status
      tags:
      - health
  /v1/videos:
    get:
      description: get latest videos
      parameters:
      - description: Max number of results
        in: query
        name: limit
        type: integer
      - description: Number of results to ignore
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/httputils.HTTPResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/ent.Video'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputils.HTTPError'
      summary: Query videos
      tags:
      - videos
    post:
      consumes:
      - application/json
      description: Create a video
      parameters:
      - description: Video title
        in: body
        maxLength: 255
        minLength: 1
        name: title
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/httputils.HTTPResponse'
            - properties:
                data:
                  $ref: '#/definitions/ent.Video'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputils.HTTPError'
      summary: Create a video
      tags:
      - videos
  /v1/videos/{id}:
    delete:
      description: Delete one video
      parameters:
      - description: Video ID
        in: path
        maxLength: 36
        minLength: 36
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httputils.HTTPResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputils.HTTPError'
      summary: Delete a video
      tags:
      - videos
    get:
      description: get one video
      parameters:
      - description: Video ID
        in: path
        maxLength: 36
        minLength: 36
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/httputils.HTTPResponse'
            - properties:
                data:
                  $ref: '#/definitions/ent.Video'
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputils.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputils.HTTPError'
      summary: Get a video
      tags:
      - videos
swagger: "2.0"
