definitions:
  ent.Video:
    properties:
      created_at:
        type: string
      id:
        type: integer
      status:
        type: string
      title:
        type: string
      updated_at:
        type: string
      uuid:
        type: string
    type: object
  v1.JSONResponse:
    properties:
      data:
        type: object
      message:
        type: string
      success:
        type: boolean
    type: object
info:
  contact: {}
  license:
    name: GNU General Public License v3.0
    url: https://github.com/dreamvo/gilfoyle/blob/master/LICENSE
paths:
  /healthcheck:
    get:
      description: get string by ID
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Check service status
  /v1/videos:
    get:
      consumes:
      - application/json
      description: get latest videos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/v1.JSONResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/ent.Video'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.JSONResponse'
      summary: Query videos
      tags:
      - Videos
    post:
      consumes:
      - application/json
      description: Create a video
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/v1.JSONResponse'
            - properties:
                data:
                  $ref: '#/definitions/ent.Video'
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.JSONResponse'
      summary: Create a video
      tags:
      - Videos
  /v1/videos/{id}:
    delete:
      consumes:
      - application/json
      description: Delete one video
      parameters:
      - description: Video ID
        in: path
        maxLength: 36
        minLength: 36
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.JSONResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.JSONResponse'
      summary: Delete a video
      tags:
      - Videos
    get:
      consumes:
      - application/json
      description: get one video
      parameters:
      - description: Video ID
        in: path
        maxLength: 36
        minLength: 36
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/v1.JSONResponse'
            - properties:
                data:
                  $ref: '#/definitions/ent.Video'
              type: object
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.JSONResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.JSONResponse'
      summary: Get a video
      tags:
      - Videos
swagger: "2.0"
