version: 2
updates:
# Enable version updates for Go modules
- package-ecosystem: gomod
  open-pull-requests-limit: 0
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  reviewers:
    - sundowndev
  assignees:
    - sundowndev
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
# Fetch and update latest `github-actions` pkgs
- package-ecosystem: github-actions
  open-pull-requests-limit: 0
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 0
  reviewers:
    - sundowndev
  assignees:
    - sundowndev
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
# Enable version updates for Docker
- package-ecosystem: "docker"
  open-pull-requests-limit: 0
  # Look for a `Dockerfile` in the `root` directory
  directory: "/.support/docker/"
  # Check for updates once a week
  schedule:
    interval: "weekly"
