before:
  hooks:
    - go generate ./...
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    binary: gilfoyle
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags: -s -w -X github.com/dreamvo/gilfoyle/config.Version={{.Version}} -X github.com/dreamvo/gilfoyle/config.Commit={{.ShortCommit}}
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      386: i386
      amd64: x86_64
    files:
      - none*
checksum:
  name_template: '{{ .ProjectName }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - '^refactor:'
      - 'Merge pull request'
      - 'Merge branch'
