services:
  db:
    dialect: postgres
    host: localhost
    port: 5432
    user: postgres
    password: secret
    db_name: gilfoyle
  redis:
    host: localhost
    port: 3482
    password: secret
  ipfs:
    gateway: gateway.ipfs.io
settings:
  max_file_size: 50mb
  serve_docs: true
