apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      run: api
  template:
    metadata:
      labels:
        run: api
    spec:
      containers:
        - image: dreamvo/gilfoyle:latest
          imagePullPolicy: Always
          name: api
          ports:
            - containerPort: 8080
              protocol: TCP
          args:
            - server
            - -p
            - 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              initialDelaySeconds: 5
              periodSeconds: 3
          readinessProbe:
            exec:
              command:
              - timeout
              - ls
              - /tmp
            initialDelaySeconds: 5
            periodSeconds: 5
